from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name='contact'),
    path('offers/', views.offers, name='offers'),
    path('destinations/', views.destinations, name='destinations'),
    path('faq/', views.faq, name='faq'),
    path('partners/', views.partners, name='partners'),
    path('testimonials/', views.testimonials, name='testimonials'),
    path('more/', views.more, name='more'),
    path('packages/', views.packages, name='packages'),
    path('booking/', views.booking, name='booking'),
    path('experiences/', views.experiences, name='experiences'),
    path('team/', views.team, name='team'),
    path('blog/', views.blog, name='blog'),
    path('blog/post-1/', views.blog_post, name='blog_post_1'),
    path('blog/post-2/', views.blog_post, name='blog_post_2'),
    path('blog/post-3/', views.blog_post, name='blog_post_3'),
    path('blog/post-4/', views.blog_post, name='blog_post_4'),
    path('blog/post-5/', views.blog_post, name='blog_post_5'),
    path('blog/post-6/', views.blog_post, name='blog_post_6'),
    path('visa/', views.visa, name='visa'),
    path('travel-guide/', views.travel_guide, name='travel_guide'),
    path('itinerary/', views.itinerary, name='itinerary'),
    path('policies/', views.policies, name='policies'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('refund/', views.refund, name='refund'),
]
