# Generated by Django 6.1 on 2026-08-14 13:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100, verbose_name='نوع التقرير')),
                ('period', models.CharField(max_length=50, verbose_name='الفترة')),
                ('data', models.JSONField(verbose_name='البيانات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تقرير الحجوزات',
                'verbose_name_plural': 'تقارير الحجوزات',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='عميل', max_length=200, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(default='0000000000', max_length=20, verbose_name='رقم الهاتف')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('customer_id', models.CharField(blank=True, max_length=50, verbose_name='رقم الهوية')),
                ('booking_type', models.CharField(choices=[('flight', '✈️ طيران'), ('hotel', '🏨 فندق'), ('tour', '🗺️ جولة سياحية'), ('train', '🚆 قطار'), ('bus', '🚌 حافلة'), ('car', '🚗 تأجير سيارة')], default='flight', max_length=50, verbose_name='نوع الحجز')),
                ('booking_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم الحجز')),
                ('destination', models.CharField(default='وجهة', max_length=200, verbose_name='الوجهة')),
                ('departure_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ المغادرة')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ العودة')),
                ('passengers', models.IntegerField(default=1, verbose_name='عدد المسافرين')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الأساسي')),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الضرائب')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصم')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('status', models.CharField(choices=[('pending', '🟡 معلق'), ('confirmed', '🟢 مؤكد'), ('cancelled', '🔴 ملغي'), ('completed', '✅ مكتمل')], default='pending', max_length=20, verbose_name='حالة الحجز')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('ticket_issued', models.BooleanField(default=False, verbose_name='تم إصدار التذكرة')),
                ('ticket_number', models.CharField(blank=True, max_length=100, verbose_name='رقم التذكرة')),
                ('ticket_file', models.FileField(blank=True, upload_to='tickets/', verbose_name='ملف التذكرة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-booking_date'],
                'permissions': [('confirm_booking', 'يمكن تأكيد الحجز'), ('issue_ticket', 'يمكن إصدار تذكرة'), ('view_reports', 'يمكن عرض التقارير')],
            },
        ),
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='الإجراء')),
                ('details', models.TextField(verbose_name='التفاصيل')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bookings.booking')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل التعديل',
                'verbose_name_plural': 'سجلات التعديلات',
                'ordering': ['-timestamp'],
            },
        ),
    ]
